### ISSUE TITLE
Clear all events / test bookings in development

### ISSUE THREAD

**Issue by karudonaldson** [Roomify/RfA#292]
While setting up a test site, test bookings are obviously being processed.  As such, you quickly find rooms being booked out and unavailable for more tests.

A couple of things raise questions:
1.  If a payment is not received, is the room put into a held state pending payment?
2.  If the held state is true, is there an easy method to clear the history of the events so rooms become available again?  I just had to manually remove 30 odd events to allow more testing in the same month.

I searched but couldn't find anything in the issue queue or the documentation.

Cheers,
Karu

**Comment by salvoscala** [comment]
Once you make a booking, the room will be not available for those dates. The payment process is "separated" from the booking itself, because you may have different use cases and payment process
At the moment there isn't a way to delete a group of bookings with the same state (commerce order state), so I guess you'll have to delete those manually.

Regards.

**Comment by karudonaldson** [comment]
Ah ok, that makes sense :)
