### ISSUE TITLE
Irritating alarming situation

### ISSUE THREAD

**Issue by ugintl** [Roomify/RfA#343]
On checking updates, I get this (see snapshot). What should I do? There are lot of unsupported modules with some security updates available. As long as I can guess by seeing the version no. of the modules, you have done customization.
![available updates new roomify](https://user-images.githubusercontent.com/12570802/34319951-5bf8ef52-e810-11e7-9dae-52bf15ebc3d7.png)

**Comment by acrollet** [comment]
We often need to use development releases in order to use specific patches or features - unfortunately, the update status module does not recognize when development releases are newer than supported releases. If you find that there's a module with a version older than a security release, please open a specific issue for that module.
