### ISSUE TITLE
After installation in Xampp PDOException 

### ISSUE THREAD

**Issue by ilichpadilla** [Roomify/RfA#400]
I followed the installation instruction using Xampp, and got error trying to view the website

See image below:
![image](https://user-images.githubusercontent.com/5929456/51010403-8d99fe00-152a-11e9-96b7-fc6b9d137770.png)

**Comment by dutchmale** [comment]
I am having the same issue. Did you already solve it and how did you solve it?

**Comment by ilichpadilla** [comment]
Hi, 
I did not solve it, I think the maintainers here should help us with this issue, but it seems this project is not having support anymore.

**Comment by acrollet** [comment]
Hello there,

this issue is not specific to RfA - you might try increasing the MySQL max allowed packet size configuration, see the results for this search:

https://www.google.com/search?safe=active&client=safari&rls=en&ei=M68DXfaOKoyisAWk_rL4CA&q=drupal+mysql+2006&oq=drupal+mysql+2006&gs_l=psy-ab.3..0i8i30.1475.1475..1773...0.0..0.73.73.1......0....1..gws-wiz.......0i71.hYXQZM08juo
